trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true

  - task: AzureStaticWebApp@0
    inputs:
      app_location: "/4thYearProject" 
      output_location: "/working_dir/4thYearProject/bin/Release/net5.0/wwwroot"
    env:
      azure_static_web_apps_api_token: $(deployment_token)