trigger:
  branches:
    include:
    - master

variables:
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UseDotNet@2
      displayName: Force .NET 5
      inputs:
        packageType: 'sdk'
        version: '5.x'
    - task: DotNetCoreCLI@2
      displayName: Restore project
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Build API
      inputs:
        command: 'build'
        projects: '**/4thYearProject.Api.csproj'
    - task: DotNetCoreCLI@2
      displayName: Build Blazor WebAssembly
      inputs:
        command: 'build'
        projects: '**/4thYearProject.Server.csproj'


- stage: Release  
  displayName: Release stage

  jobs:
  - job: Release
    displayName: Release to Azure

    pool:
        vmImage: $(vmImageName)
    steps:
    - task: UseDotNet@2
      displayName: Force .NET 5
      inputs:
        packageType: 'sdk'
        version: '5.x'
    - task: DotNetCoreCLI@2
      displayName: Restore project
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Publish project
      inputs:
        command: 'publish'
        publishWebProjects: true
        projects: '**/*.csproj'
    - task: AzureRmWebAppDeployment@4
      displayName: Deploy to Azure
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'fotostop'
        appType: 'webApp'
        WebAppName: 'fotostopAPI'
        packageForLinux: '$(System.DefaultWorkingDirectory)/4thYearProject.Api/*.zip'
    - task: AzureRmWebAppDeployment@4
      displayName: Deploy Blazor WebAssembly to Azure
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'fotostop'
        appType: 'webApp'
        WebAppName: 'fotostopBlazor'
        packageForLinux: '$(System.DefaultWorkingDirectory)/4thYearProject/*.zip'