trigger:
  branches:
    include:
    - master

variables:
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build

  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UseDotNet@2
      displayName: Force .NET 5
      inputs:
        packageType: 'sdk'
        version: '5.x'
    - task: DotNetCoreCLI@2
      displayName: Restore project
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Build API
      inputs:
        command: 'build'
        projects: '**/4thYearProject.Api.csproj'
    - task: DotNetCoreCLI@2
      displayName: Build Identity Server
      inputs:
        command: 'build'
        projects: '**/FourthYearProject.IDP.csproj'
    - task: DotNetCoreCLI@2
      displayName: Build Blazor WebAssembly
      inputs:
        command: 'build'
        projects: '**/4thYearProject.Server.csproj'


- stage: Testing 
  displayName: Testing

  jobs:
  - job: Running Unit Tests...
    displayName: Release to Azure

    pool:
        vmImage: $(vmImageName)
    steps:
    - task: UseDotNet@2
      displayName: Force .NET 5
      inputs:
        packageType: 'sdk'
        version: '5.x'
    - task: DotNetCoreCLI@2
      displayName: Restore project
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Running Unit Tests
      inputs:  
        command: test
        projects: '**/FourthYearProject.UnitTesting'
        arguments: '--configuration Release'

- stage: Release  
  displayName: Release stage

  jobs:
  - job: Release
    displayName: Release to Azure

    pool:
        vmImage: $(vmImageName)
    steps:
    - task: UseDotNet@2
      displayName: Force .NET 5
      inputs:
        packageType: 'sdk'
        version: '5.x'
    - task: DotNetCoreCLI@2
      displayName: Restore project
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Publish project
      inputs:
        command: 'publish'
        publishWebProjects: true
        projects: '**/*.csproj'
    - task: AzureRmWebAppDeployment@4
      displayName: Deploy API to Azure
      inputs:
        ConnectionType: AzureRM
        azureSubscription: fotostop
        appType: 'webApp'
        WebAppName: 'fotostopAPI'
        package: $(System.DefaultWorkingDirectory)/4thYearProject.Api
        DeploymentType: 'webDeploy'
        enableCustomDeployment: true

    - task: AzureRmWebAppDeployment@4
      displayName: Deploy Identity Server to Azure
      inputs:
        ConnectionType: AzureRM
        azureSubscription: fotostop
        appType: 'webApp'
        WebAppName: 'fotostopIDP'
        package: $(System.DefaultWorkingDirectory)/FourthYearProject.IDP
        DeploymentType: 'webDeploy'
        enableCustomDeployment: true



- stage: Blazor  
  displayName: Blazor

  jobs:
  - job: Blazor
    displayName: Release to Azure

    pool:
        vmImage: "ubuntu-latest"
    steps:
    - task: UseDotNet@2
      displayName: Force .NET 5
      inputs:
        packageType: 'sdk'
        version: '5.x'
    - task: DotNetCoreCLI@2
      displayName: Restore project
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Publish project
      inputs:
        command: 'publish'
        publishWebProjects: true
        projects: '**/*.csproj'
    - task: AzureStaticWebApp@0
      displayName: Blazor Deploy to Azure Static Web Apps
      inputs:
        app_location: "/4thYearProject" 
        output_location: "wwwroot"
      env:
        azure_static_web_apps_api_token: $(deployment_token)